### ISSUE TITLE
links in readme 404

### ISSUE THREAD

**Issue by pixelass** [sinnerschrader/BlueantJS#2]
All links inside the readme.md direct to a 404. (old gitlab links?)

Also there is a mention  of "WEB-INF/conf/axis2.xml" which I could not find in this project.

**Comment by flobbie** [comment]
"All links"?
There are three links, wsdl2html.html, src/blueant.ts and localhost:3000.
The first two are working.

Which links do you mean?

**Comment by pixelass** [comment]
I clicked a few links which led to a Gitlab/404. I'll send you a PR in a bit.

**Comment by pixelass** [comment]
Also. I now get that the mentioned xml is part of the böueant instance.
