### ISSUE TITLE
documentation for vanillaJS

### ISSUE THREAD

**Issue by pixelass** [sinnerschrader/BlueantJS#3]
The minimal documentation in the readme does not help people who don't know typescript. I think it would be better to use a more consistent documentation format (e.g. jsdoc) to generate a documentation or change the readme to use vanilla JS.

**Comment by flobbie** [comment]
Maybe you can try https://www.npmjs.com/package/tsdoc
This package may generate the correct jsdoc from typescript projects.

**Comment by pixelass** [comment]
Kk. Will try. Thx for the fast response
